name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "🚀 Starting deployment..."

            # Loyiha papkasiga o'tish
            cd /opt/notifications_app

            # Git fetch va reset (merge conflict bo'lmasligi uchun)
            echo "📥 Fetching latest changes from GitHub..."
            git fetch origin main
            git reset --hard origin/main
            git clean -fd

            # Python dependencies ni yangilash
            echo "📦 Installing/updating dependencies..."
            pip3 install -r requirements.txt || echo "requirements.txt topilmadi"

            # Service ni qayta ishga tushirish
            echo "🔄 Restarting service..."
            sudo systemctl restart olx-bot.service

            # Status tekshirish
            echo "✅ Checking service status..."
            sudo systemctl status olx-bot.service --no-pager

            echo "🎉 Deployment completed successfully!"
